export const projects = [
  {
    title: 'sdanundverkauf.de',
    description: "Auf dieser Website kann jeder Benutzer aktuelle Informationen zu den aktuellen Gold- und Silberpreisen erhalten und entscheiden, ob er seine alten Gold- oder Silberprodukte an meinen Kunden verkaufen möchte. Es gibt auch einen Rechner, der dem Benutzer eine Schätzung geben kann, wie viel er für seine Produkte bekommen könnte, bevor er tatsächlich zum Geschäft geht.",
    image: '/images/6.png',
    tags: ['Next.js', 'PHP', 'styled-components'],
    code: 'https://github.com/mihaimazareanu/sdanundverkauf',
    visit: 'https://sdanundverkauf.de',
    id: 0,
  },
  {
    title: 'kidsFi',
    description: "kidsFi ist eine Next.js-App, die Kindern Finanzthemen näherbringt. Sie ermöglicht es ihnen, ihr Sparschwein, ihr Sparkonto und den Zinssatz zu verfolgen. Mit MongoDB, styled-components und Figma entwickelt, bietet sie eine einfache und ansprechende Möglichkeit für Kinder, mehr über persönliche Finanzen zu lernen.",
    image: '/images/4.png',
    tags: ['Next.js', 'MongoDB', 'styled-components'],
    code: 'https://github.com/mihaimazareanu/capstone-project-kidsfi',
    visit: 'https://kidsfi.vercel.app/',
    id: 1,
  },
   {
    title: 'm-m-residence',
    description: "M-M-Residence ist eine Next.js-App, die Gästen Details über mein und das Zuhause meiner Frau auflistet, das auf HomeExchange.com angeboten wird. Ihre einfache Benutzeroberfläche ist benutzerfreundlich und bietet Gästen alles, was sie wissen müssen, um einen angenehmen und komfortablen Aufenthalt zu haben.",
    image: '/images/5.png',
    tags: ['Next.js', 'MongoDB', 'styled-components'],
    code: 'https://github.com/mihaimazareanu/m-m-residence',
    visit: 'https://m-m-residence.vercel.app/',
    id: 2,
  },
  {
    title: "Mock GPT3-Clone",
    description: "Diese App ist eine beeindruckende Nachbildung der Benutzeroberfläche von OpenAI's GPT-3, erstellt mit React.js und CSS. Erfahren Sie, wie gutes Design Ihre App modern und elegant aussehen lassen kann, indem Sie Figma als Design-Tool verwenden. Verleihen Sie Ihrer App einen Höhenflug und begeistern Sie Ihr Publikum auf neue und aufregende Weise.",
    image: '/images/1.png',
    tags: ['React.js', 'CSS', 'Figma'],
    visit: 'https://gpt3-clone-gamma.vercel.app/',
    code: 'https://github.com/mihaimazareanu/gpt3-clone',
    id: 3,
  },
  {
    title: 'Gericht Restaurant',
    description:"Diese App ist eine optisch ansprechende, fiktive Landing Page für ein Restaurant, die mit Figma entworfen und mit CSS gestaltet wurde. Obwohl sie keine Funktionalität bietet, dient sie als hervorragendes Beispiel für das Potenzial zur Erstellung moderner und ansprechender Webseiten mit React.js-Komponenten. Das responsive Design gewährleistet eine optimale Darstellung auf allen Geräten.",
    image: '/images/2.png',
    tags: ['React.js', 'CSS', 'Figma'],
    code: 'https://github.com/mihaimazareanu/gerich-restaurant',
    visit: 'https://gerich-restaurant-omega.vercel.app/',
    id: 4,
  },
  {
    title: 'Modern Business App',
    description: "Diese React.js-App wurde mit dem Vite-Framework erstellt und präsentiert ein modernes Webseiten-Design für eine Bank. Sie bietet reaktionsfähige Komponenten und effiziente Build-Zeiten, um ein nahtloses Benutzererlebnis zu gewährleisten. Die App dient als Beispiel für modernes Webdesign mit Schwerpunkt auf Layout und Reaktionsfähigkeit.",
      image: '/images/3.png',
      tags: ['React.js', 'Vite', "TailwindCSS", "Figma"],
    code: 'https://github.com/mihaimazareanu/business-modern-app-vite',
    visit: 'https://business-modern-app.vercel.app/',
    id: 5,
  },  
];